services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    #image: keycloak:24.0.4
    #build:
    #  context: .
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - 8080:8080
    command:
      - start-dev
      - --import-realm
    volumes:
      #- ./target/fksdb-keycloak-user-provider-0.0.1.jar:/opt/keycloak/providers/fksdb-provider.jar
      - /home/adam/Documents/git/keycloak-quickstarts/extension/user-storage-jpa/target/user-storage-jpa-example.jar:/opt/keycloak/providers/fksdb-provider.jar
      - ./conf/quarkus.properties:/opt/keycloak/conf/quarkus.properties:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
