services:
  keycloak:
    image: 'keycloak'
    build:
      context: .
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    command:
      - start-dev
      - --import-realm
