name: keycloak

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - 8080:8080
    command:
      - start-dev
      - --import-realm
    volumes:
      - ../target/fksdb-keycloak-user-provider.jar:/opt/keycloak/providers/fksdb-provider.jar
      - ./config:/opt/keycloak/conf
      - ../fksdb-theme:/opt/keycloak/themes/fksdb-theme
    extra_hosts:
      - "host.docker.internal:host-gateway"
